added frontend and backend job to the workflows

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,36 +1,36 @@
 version: 2.1
 
-commands:
-  desctroy-environment:
-    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-    parameters:
-      # Add parameters here
-    steps:
-      - run:
-          name: Destroy environments
-          when: on_fail
-          command: /
-            # Your code here
-            exit 1
+# commands:
+#   desctroy-environment:
+#     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+#     parameters:
+#       # Add parameters here
+#     steps:
+#       - run:
+#           name: Destroy environments
+#           when: on_fail
+#           command: /
+#             # Your code here
+#             exit 1
 
-  revert-migration:
-    description: Revert the last migration if successfully run in current workflow.
-    parameters:
-      # Add parameter here
-    steps:
-      - run:
-          name: Revert migrations
-          # Add when this will run
-          command: /
-            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
-            if(( $SUCCESS==1 )); 
-            then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
-            fi
+#   revert-migration:
+#     description: Revert the last migration if successfully run in current workflow.
+#     parameters:
+#       # Add parameter here
+#     steps:
+#       - run:
+#           name: Revert migrations
+#           # Add when this will run
+#           command: /
+#             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+#             SUCCESS = 1
+#             if(( $SUCCESS==1 )); 
+#             then
+#             #  cd ~/project/backend
+#             #  npm install
+#             #  Add revert code here. You can find this in the Getting Started section.
+#               exit 1
+#             fi
 
 jobs:
   build_frontend:
@@ -48,27 +48,44 @@ jobs:
             npm run build
       - save_cache:
           paths: [frontend/node_modules]
-          keys: frontend-build
+          key: frontend-build
+  build_backend:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Build backend
+          command: \
+            cd backend
+            npm install
+            npm run build
+      - save_cache:
+          paths: [backend/node_modules]
+          key: backend-build
 
-cleanup:
-  docker:
-    - image: cicleci/node:18.3.0
-  steps:
-    - run:
-        name: get old stack workflow id
-        command: /
-          # your code here
-          export OldWorkflowID="the id here"
-          export STACKS=[] #put the list of stacks here
-    - run:
-        name: Remove old stacks and files
-        command: /
-          if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-          then
-            # your code here
-          fi
+# cleanup:
+#   docker:
+#     - image: cicleci/node:18.3.0
+#   steps:
+#     - run:
+#         name: get old stack workflow id
+#         command: /
+#           # your code here
+#           export OldWorkflowID="the id here"
+#           export STACKS=[] #put the list of stacks here
+#     - run:
+#         name: Remove old stacks and files
+#         command: /
+#           if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+#           then
+#             # your code here
+#           fi
 
 workflows:
   default:
     jobs:
-      - build-frontend
+      - build_frontend
+      - build_backend
